server:
  port: 8005


spring:
  application:
    name: tcsoft-data-platform-kafka-consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: false

    stream:
      kafka:
        binder:
          brokers: 106.14.77.81:9092
          #          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        input:
          destination: stream-demo02
          content-type: application/json
          group: test
          consumer:
            partitioned: true   #开启分区
      instance-count: 1     #分区数量
