server:
  port: 8005


spring:
  application:
    name: tcsoft-data-platform-kafka-consumer

#  datasource:
#    username: root
#    password: 12345678
#    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&userUnicode=true&CharacterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: false

    stream:
      kafka:
        binder:
          brokers: localhost:9092
          #          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        input:
          destination: stream-demo
          group: test

