server:
  port: 8001
#  servlet:
#    context-path: /security

spring:
  application:
    name: tcsoft-data-platform-security

  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&userUnicode=true&CharacterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# JWT 参数配置
jwt:
  header: Authorization
  secret: "ycjkskdmflsamewqjfnfkqwndkqw99d-dsa-dsam=dmas-sakdieiemlsm"
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"