server:
  port: 8006
  servlet:
    context-path: /setting

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false   # 关闭驼峰命名


spring:
  application:
    name: tcsoft-data-platform-system-setting

  datasource:
    username: root
    password: TCsoft123..
    url: jdbc:mysql://106.14.77.81:3306/systemConfiguration?serverTimezone=Asia/Shanghai&userUnicode=true&CharacterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置数据库监控druid
    druid:
      # 记录慢的sql
      filter:
        stat:
          log-slow-sql: true
          enabled: true
          slow-sql-millis: 2000
      # 开启过滤器
      filters: stat,wall,log4j2
      # 启用stat-filter
      web-stat-filter:
        enabled: true
        url-pattern: "/**"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000

      ##### StatViewServlet配置 #######
      #启用内置的监控页面
      stat-view-servlet:
        enabled: true
        #内置监控页面的地址
        url-pattern: /druid/*
        #关闭 Reset All 功能
        reset-enable: false
        #设置登录用户名
        login-username: admin
        #设置登录密码
        login-password: 123
        #白名单（如果allow没有配置或者为空，则允许所有访问）
        allow: 127.0.0.1
        #黑名单（deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝）
#        deny:



  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.3.3:8848
        server-addr: 106.14.77.81:8848

