server:
  port: 8003


spring:
  application:
    name: tcsoft-data-platform-kafka-provider

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    stream:
      kafka:
        binder:
          brokers: localhost:9092         #Kafka的消息中间件服务器
#          zk-nodes: localhost:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true        #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。
          auto-add-partitions: true
      bindings:
        output:      #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: sample    #消息发往的目的地
#          content-type: text/plain    #消息发送的格式，接收端不用指定格式，但是发送端要
          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要
          producer:
            partitionCount: 2
        input:
          destination: sample
          group: test-consumer-group
          consumer:
            partitioned: true   #开启分区
            instance-count: 1


#      bindings:
#        output:                             #这里用stream给我们提供的默认output，后面会讲到自定义output
#          destination: stream-demo02                 #消息发往的目的地
#          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要
#          producer:
#            partitionKeyExpression: payload.id   #分区的主键，根据什么来分区，下面的payload.id只是一个对象的id用于做为Key，用来说明的。希望不要误解
#            partitionCount: 1    #Key和分区数量进行取模去分配消息，这里分区数量配置为2





