server:
  port: 8003


spring:
  application:
    name: tcsoft-data-platform-kafka-provider

#  datasource:
#    username: root
#    password: 12345678
#    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=Asia/Shanghai&userUnicode=true&CharacterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.3:8848
    sentinel:
      transport:
        dashboard: 192.168.3.3:8888
      eager: false

    stream:
      kafka:
        binder:
          brokers: 106.14.77.81:9092           #Kafka的消息中间件服务器
#          zk-nodes: 192.168.3.3:2181        #Zookeeper的节点，如果集群，后面加,号分隔
          auto-create-topics: true          #如果设置为false,就不会自动创建Topic 有可能你Topic还没创建就直接调用了。

      bindings:
        output:                             #这里用stream给我们提供的默认output，后面会讲到自定义output
          destination: stream-demo02                 #消息发往的目的地
          content-type: application/json    #消息发送的格式，接收端不用指定格式，但是发送端要
          producer:
#            partitionKeyExpression: payload.id   #分区的主键，根据什么来分区，下面的payload.id只是一个对象的id用于做为Key，用来说明的。希望不要误解
            partitionCount: 2    #Key和分区数量进行取模去分配消息，这里分区数量配置为2





