server:
  port: 8888


jwt:
  # 秘钥
  secret: "qazwsxedcrfvtgbyhnujmdssaftghyujkloipmnvgyuhikolp"

spring:
  application:
    name: tcsoft-data-platform-gateway
  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.3.3:8848
        server-addr: 106.14.77.81:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true
#      routes:
#        - id: tcsoft-data-platform-security # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          #匹配后提供服务的路由地址
##          uri: http://localhost:8001
#          uri: lb://tcsoft-data-platform-security
#          predicates:
#            - Host=**
#
#        - id: tcsoft-data-platform-system-setting
#          uri: lb://tcsoft-data-platform-system-setting
#          predicates:
#            - Host=**
#            - Method=POST
#            - Path=/com.tcsoft.security/** #断言,路径相匹配的进行路由
#            - Path=/payment/get/** # 断言，路径相匹配的进行路由
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
#            - Host=**

#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
#           过滤
#          filters:
#            - AddRequestHeader=X-Request-red, blue
#        - id: tcsoft-data-platform-service
#          uri: lb://tcsoft-data-platform-service
#          predicates:
#            - Method=GET
#            - Path=/service/** #断言,路径相匹配的进行路由
