server:
  port: 8888

jwt:
  # 秘钥
  secret: "qazwsxedcrfvtgbyhnujmdssaftghyujkloipmnvgyuhikolp"
  userId: 1

spring:
  application:
    name: tcsoft-data-platform-gateway

  redis:
    host: 106.14.77.81
    port: 6379
    password: TCsoft123..
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

  cloud:
    nacos:
      discovery:
#        server-addr: 192.168.3.3:8848
        server-addr: 106.14.77.81:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true
