server:
  port: 8004


spring:
  application:
    name: tcsoft-data-platform-kafka-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.3:8848

    stream:
      kafka:
        binder:
          brokers: 192.168.3.3:9092
#          zk-nodes: localhost:2181
          auto-create-topics: true
      bindings:
        input:
          destination: sample
          group: test-consumer-group
          consumer:
            partitioned: true   #开启分区

