server:
  port: 8010


spring:
#  data:
#    mongodb:
#      host: 192.168.3.3
#      port: 27017
#      database: test

  redis:
    host: 106.14.77.81
    port: 6379
    password: TCsoft123..
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-wait: 300ms
        max-idle: 16
        min-idle: 8

  application:
    name: tcsoft-data-platform-service

  datasource:
    username: root
    password: TCsoft123..
    url: jdbc:mysql://106.14.77.81:3306/systemConfiguration?serverTimezone=Asia/Shanghai&userUnicode=true&CharacterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 106.14.77.81:8848
    sentinel:
      transport:
        dashboard: 106.14.77.81:8080
      eager: false

